name: infra
description: A minimal Azure Native Python Pulumi program


backend:
  url: https://app.pulumi.com/Wichtowski

runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: azure-python
