name: Deploy All to Azure

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - production
          - staging
          - development

jobs:
  deploy-frontend:
    name: Deploy Frontend
    uses: ./.github/workflows/deploy-frontend.yaml
    with:
      environment: ${{ inputs.environment || 'production' }}

  deploy-infra:
    name: Deploy Infrastructure
    uses: ./.github/workflows/deploy-infra.yaml
    with:
      environment: ${{ inputs.environment || 'production' }}
