name: Deploy on Development

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Name of GitHub Source Branch or Tag'
        required: true
        type: string
        default: 'main'
      semantic-version:
        type: choice
        description: 'Semantic version'
        required: true
        options:
          - 'minor'
          - 'patch'
          - 'major'
        default: 'minor'
      bump-version:
        type: choice
        description: 'Do you want to bump a version?'
        options:
          - 'no'
          - 'yes'
        default: 'no'

  # push:
  #   branches:
  #     - main
  #     - tags

permissions: write-all

concurrency:
  group: deploy-dev
  cancel-in-progress: false

jobs:
  release-new-version:
    name: 'Release new version'
    uses: ./.github/workflows/release-new-version.yml
    with:
      bump-version: ${{ inputs.bump-version || 'yes' }}
      branch-name: ${{ inputs.branch-name || 'main' }}
      semantic-version: ${{ inputs.semantic-version || 'minor' }}
    secrets: inherit

  deploy-on-dev:
    name: Deploy on Dev
    needs: release-new-version
    uses: ./.github/workflows/deploy-on-env.yaml
    with:
        environment: 'development'
        source-name: ${{ needs.release-new-version.outputs.new-tag || inputs.branch-name || 'main' }}
    secrets: inherit
