name: Deploy on Environment

on:
  push:
    branches: [main]

  workflow_call:
    inputs:
      source-name:
        description: "Source name to deploy from"
        required: true
        type: string
        default: "main"
      environment:
        description: "Environment to deploy to"
        required: true
        type: string
        default: "production"

jobs:
  deploy-frontend:
    name: Deploy Frontend
    uses: ./.github/workflows/deploy-frontend.yaml
    with:
      environment: ${{ inputs.environment || 'production' }}
      source-name: ${{ inputs.source-name || 'main' }}

  deploy-infra:
    name: Deploy Infrastructure
    uses: ./.github/workflows/deploy-infra.yaml
    with:
      environment: ${{ inputs.environment || 'production' }}
      source-name: ${{ inputs.source-name || 'main' }}
