name: Deploy All to Azure

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - production
          - staging
          - development

env: 
  environment: ${{ inputs.environment || 'production' }}

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/deploy-frontend.yaml
        with:
          environment: ${{ env.environment }}

  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/deploy-infra.yaml
        with:
          environment: ${{ env.environment }}
