name: Deploy on Environment

on:
  workflow_call:
    inputs:
      source-name:
        description: "Source name to deploy from"
        required: true
        type: string
        default: "main"
      environment:
        description: "Environment to deploy to"
        required: true
        type: string
        default: "production"

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'production' }}
    uses: ./.github/workflows/deploy-infra.yaml
    with:
      environment: ${{ inputs.environment || 'production' }}
      source-name: ${{ inputs.source-name || 'main' }}
    secrets: inherit

  deploy-frontend:
    name: Deploy Frontend
    needs: deploy-infra
    uses: ./.github/workflows/deploy-frontend.yaml
    with:
      environment: ${{ inputs.environment || 'production' }}
      source-name: ${{ inputs.source-name || 'main' }}
    secrets: inherit