name: Deploy Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: string
        default: "production"
      source-name:
        description: "Source name to deploy from"
        required: true
        type: string
        default: "main"
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      PULUMI_CONFIG_PASSPHRASE:
        required: true

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - production
          - staging
          - development
        default: "production"
      source-name:
        description: "Source name to deploy from"
        required: true
        type: string
        default: "main"

env:
  infra_dir: ./infra

permissions: write-all

jobs:
  build-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Install dependencies
        working-directory: ${{ env.infra_dir }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Install Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: federated

      - name: Azure CLI
        uses: azure/cli@v2
        with:
          azcli-version: latest
          inlineScript: |
            az account show

      - name: Deploy Infrastructure
        working-directory: ${{ env.infra_dir }}
        run: |
          pulumi login
          pulumi stack select ${{ inputs.environment }}
          pulumi up --yes
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
