name: Python PR Checks

on:
  pull_request:
    paths:
      - 'infra/**'
      - '.github/workflows/python-checks.yaml'

jobs:
  python-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./infra
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Run Ruff
        working-directory: ./infra
        run: ruff check . 
